#cloud-config
write_files:
  - path: /etc/suricata/suricata.yaml.bak
    content: |
      %YAML 1.1
      ---
      vars:
        address-groups:
          HOME_NET: "[192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,{0}/32]"
          EXTERNAL_NET: "!$HOME_NET"
          HTTP_SERVERS: "$HOME_NET"
          SMTP_SERVERS: "$HOME_NET"
          SQL_SERVERS: "$HOME_NET"
          DNS_SERVERS: "$HOME_NET"
          TELNET_SERVERS: "$HOME_NET"
          AIM_SERVERS: "$EXTERNAL_NET"
          DC_SERVERS: "$HOME_NET"
          DNP3_SERVER: "$HOME_NET"
          DNP3_CLIENT: "$HOME_NET"
          MODBUS_CLIENT: "$HOME_NET"
          MODBUS_SERVER: "$HOME_NET"
          ENIP_CLIENT: "$HOME_NET"
          ENIP_SERVER: "$HOME_NET"
        port-groups:
          HTTP_PORTS: "80"
          SHELLCODE_PORTS: "!80"
          ORACLE_PORTS: 1521
          SSH_PORTS: 22
          DNP3_PORTS: 20000
          MODBUS_PORTS: 502
          FILE_DATA_PORTS: "[$HTTP_PORTS,110,143]"
          FTP_PORTS: 21
          GENEVE_PORTS: 6081
          VXLAN_PORTS: 4789
          TEREDO_PORTS: 3544
      default-log-dir: /var/log/suricata/
      stats:
        enabled: yes
        interval: 8
      outputs:
        - fast:
            enabled: yes
            filename: fast.log
            append: yes
        - eve-log:
            enabled: yes
            filetype: regular 
            filename: eve.json
            pcap-file: false
            community-id: false
            community-id-seed: 0
            xff:
              enabled: no
              mode: extra-data
              deployment: reverse
              header: X-Forwarded-For
            types:
              - alert:
                  tagged-packets: yes
              - anomaly:
                  enabled: yes
                  types:
              - http:
                  extended: yes     
              - dns:
              - tls:
                  extended: yes     
              - files:
                  force-magic: no   
              - smtp:
              - ftp
              - rdp
              - nfs
              - smb
              - tftp
              - ikev2
              - dcerpc
              - krb5
              - snmp
              - rfb
              - sip
              - dhcp:
                  enabled: yes
                  extended: no
              - ssh
              - mqtt:
              - stats:
                  totals: yes       
                  threads: no       
                  deltas: no        
              - flow
        - http-log:
            enabled: no
            filename: http.log
            append: yes
        - tls-log:
            enabled: no  
            filename: tls.log 
            append: yes
        - tls-store:
            enabled: no
        - pcap-log:
            enabled: no
            filename: log.pcap
            limit: 1000mb
            max-files: 2000
            compression: none
            mode: normal 
            use-stream-depth: no 
            honor-pass-rules: no 
        - alert-debug:
            enabled: no
            filename: alert-debug.log
            append: yes
        - alert-prelude:
            enabled: no
            profile: suricata
            log-packet-content: no
            log-packet-header: yes
        - stats:
            enabled: yes
            filename: stats.log
            append: yes       
            totals: yes       
            threads: no       
        - syslog:
            enabled: no
            facility: local5
        - file-store:
            version: 2
            enabled: no
            xff:
              enabled: no
              mode: extra-data
              deployment: reverse
              header: X-Forwarded-For
        - tcp-data:
            enabled: no
            type: file
            filename: tcp-data.log
        - http-body-data:
            enabled: no
            type: file
            filename: http-data.log
        - lua:
            enabled: no
            scripts:
      logging:
        default-log-level: notice
        default-output-filter:
        outputs:
        - console:
            enabled: yes
        - file:
            enabled: yes
            level: info
            filename: suricata.log
        - syslog:
            enabled: no
            facility: local5
            format: "[%i] <%d> -- "
      af-packet:
        - interface: glbint
          threads: 2
          defrag: no
          cluster-type: cluster_flow
          cluster-id: 98
          copy-mode: ips
          copy-iface: glbext
          buffer-size: 64535
          use-mmap: yes
        - interface: glbext
          threads: 2
          cluster-id: 97
          defrag: no
          cluster-type: cluster_flow
          copy-mode: ips
          copy-iface: glbint
          buffer-size: 64535
          use-mmap: yes
        - interface: default
      pcap:
        - interface: eth0
        - interface: default
      pcap-file:
        checksum-checks: auto
      app-layer:
        protocols:
          rfb:
            enabled: yes
            detection-ports:
              dp: 5900, 5901, 5902, 5903, 5904, 5905, 5906, 5907, 5908, 5909
          mqtt:
          krb5:
            enabled: yes
          snmp:
            enabled: yes
          ikev2:
            enabled: yes
          tls:
            enabled: yes
            detection-ports:
              dp: 443
          dcerpc:
            enabled: yes
          ftp:
            enabled: yes
          rdp:
          ssh:
            enabled: yes
          http2:
            enabled: no
            http1-rules: no
          smtp:
            enabled: yes
            raw-extraction: no
            mime:
              decode-mime: yes
              decode-base64: yes
              decode-quoted-printable: yes
              header-value-depth: 2000
              extract-urls: yes
              body-md5: no
            inspected-tracker:
              content-limit: 100000
              content-inspect-min-size: 32768
              content-inspect-window: 4096
          imap:
            enabled: detection-only
          smb:
            enabled: yes
            detection-ports:
              dp: 139, 445
          nfs:
            enabled: yes
          tftp:
            enabled: yes
          dns:
            tcp:
              enabled: yes
              detection-ports:
                dp: 53
            udp:
              enabled: yes
              detection-ports:
                dp: 53
          http:
            enabled: yes
            libhtp:
              default-config:
                personality: IDS
                request-body-limit: 100kb
                response-body-limit: 100kb
                request-body-minimal-inspect-size: 32kb
                request-body-inspect-window: 4kb
                response-body-minimal-inspect-size: 40kb
                response-body-inspect-window: 16kb
                response-body-decompress-layer-limit: 2
                http-body-inline: auto
                swf-decompression:
                  enabled: yes
                  type: both
                  compress-depth: 100kb
                  decompress-depth: 100kb
                double-decode-path: no
                double-decode-query: no
              server-config:
          modbus:
            enabled: no
            detection-ports:
              dp: 502
            stream-depth: 0
          dnp3:
            enabled: no
            detection-ports:
              dp: 20000
          enip:
            enabled: no
            detection-ports:
              dp: 44818
              sp: 44818
          ntp:
            enabled: yes
          dhcp:
            enabled: yes
          sip:
      asn1-max-frames: 256
      coredump:
        max-dump: unlimited
      host-mode: auto
      unix-command:
        enabled: auto
      legacy:
        uricontent: enabled
      engine-analysis:
        rules-fast-pattern: yes
        rules: yes
      pcre:
        match-limit: 3500
        match-limit-recursion: 1500
      host-os-policy:
        windows: [0.0.0.0/0]
        bsd: []
        bsd-right: []
        old-linux: []
        linux: []
        old-solaris: []
        solaris: []
        hpux10: []
        hpux11: []
        irix: []
        macos: []
        vista: []
        windows2k3: []
      defrag:
        memcap: 32mb
        hash-size: 65536
        trackers: 65535 
        max-frags: 65535 
        prealloc: yes
        timeout: 60
      flow:
        memcap: 128mb
        hash-size: 65536
        prealloc: 10000
        emergency-recovery: 30
      vlan:
        use-for-tracking: true
      flow-timeouts:
        default:
          new: 30
          established: 300
          closed: 0
          bypassed: 100
          emergency-new: 10
          emergency-established: 100
          emergency-closed: 0
          emergency-bypassed: 50
        tcp:
          new: 60
          established: 600
          closed: 60
          bypassed: 100
          emergency-new: 5
          emergency-established: 100
          emergency-closed: 10
          emergency-bypassed: 50
        udp:
          new: 30
          established: 300
          bypassed: 100
          emergency-new: 10
          emergency-established: 100
          emergency-bypassed: 50
        icmp:
          new: 30
          established: 300
          bypassed: 100
          emergency-new: 10
          emergency-established: 100
          emergency-bypassed: 50
      stream:
        memcap: 64mb
        checksum-validation: yes      
        inline: auto                  
        reassembly:
          memcap: 256mb
          depth: 1mb                  
          toserver-chunk-size: 2560
          toclient-chunk-size: 2560
          randomize-chunk-size: yes
      host:
        hash-size: 4096
        prealloc: 1000
        memcap: 32mb
      decoder:
        teredo:
          enabled: true
          ports: $TEREDO_PORTS 
        vxlan:
          enabled: true
          ports: $VXLAN_PORTS 
        vntag:
          enabled: false
        geneve:
          enabled: true
          ports: $GENEVE_PORTS 
      detect:
        profile: medium
        custom-values:
          toclient-groups: 3
          toserver-groups: 25
        sgh-mpm-context: auto
        inspection-recursion-limit: 3000
        prefilter:
          default: mpm
        grouping:
        profiling:
          grouping:
            dump-to-disk: false
            include-rules: false      
            include-mpm-stats: false
      mpm-algo: auto
      spm-algo: auto
      threading:
        set-cpu-affinity: no
        cpu-affinity:
          - management-cpu-set:
              cpu: [ 0 ]  
          - receive-cpu-set:
              cpu: [ 0 ]  
          - worker-cpu-set:
              cpu: [ "all" ]
              mode: "exclusive"
              prio:
                low: [ 0 ]
                medium: [ "1-2" ]
                high: [ 3 ]
                default: "medium"
        detect-thread-ratio: 1.0
      luajit:
        states: 128
      profiling:
        rules:
          enabled: yes
          filename: rule_perf.log
          append: yes
          limit: 10
          json: yes
        keywords:
          enabled: yes
          filename: keyword_perf.log
          append: yes
        prefilter:
          enabled: yes
          filename: prefilter_perf.log
          append: yes
        rulegroups:
          enabled: yes
          filename: rule_group_perf.log
          append: yes
        packets:
          enabled: yes
          filename: packet_stats.log
          append: yes
          csv:
            enabled: no
            filename: packet_stats.csv
        locks:
          enabled: no
          filename: lock_stats.log
          append: yes
        pcap-log:
          enabled: no
          filename: pcaplog_stats.log
          append: yes
      nfq:
      nflog:
        - group: 2
          buffer-size: 18432
        - group: default
          qthreshold: 1
          qtimeout: 100
          max-size: 20000
      capture:
      netmap:
      - interface: eth2
      - interface: default
      pfring:
        - interface: eth0
          threads: auto
          cluster-id: 99
          cluster-type: cluster_flow
        - interface: default
      ipfw:
      napatech:
          streams: ["0-3"]
          enable-stream-stats: no
          auto-config: yes
          hardware-bypass: yes
          inline: no
          ports: [0-1,2-3]
          hashmode: hash5tuplesorted
      default-rule-path: /var/lib/suricata/rules
      rule-files:
        - suricata.rules
      classification-file: /etc/suricata/classification.config
      reference-config-file: /etc/suricata/reference.config
  - path: /usr/lib/networkd-dispatcher/routable.d/90-vxlan-up
    owner: root:root
    permissions: '0755'
    content: |
      #!/bin/bash
      # filename: 90-vxlan-up
      # eth0 wan interface
      # eth1 lan interface which receives vxlan from gateway load balancer      
      if [ "$IFACE" == "eth1" ]; then
        ip rule add from ${{IP_ADDRS%% *}} to 168.63.129.16 lookup glbrt
        ip route add 168.63.129.16 via 10.110.1.1 dev $IFACE table glbrt   
        ip link add glbint type vxlan id 800 remote 10.110.1.128 dstport 10800 dev $IFACE
        ip link set glbint up
        ip link add glbext type vxlan id 801 remote 10.110.1.128 dstport 10801 dev $IFACE
        ip link set glbext up
        ip link set $IFACE mtu 4000
        ip link set glbint mtu 3900
        ip link set glbext mtu 3900
        systemctl start suricata
      fi
  - path: /usr/lib/networkd-dispatcher/off.d/90-vxlan-down
    owner: root:root
    permissions: '0755'
    content: |
      #!/bin/bash
      # filename: 90-vxlan-down
      if [ "$IFACE" == "eth1" ]; then
        ip link delete glbext type vxlan
        ip link delete glbint type vxlan
        systemctl stop suricata
      fi
  - path: /etc/iproute2/rt_tables
    content: |
      128 glbrt 
    append: true
runcmd:
  - add-apt-repository ppa:oisf/suricata-stable -y
  - apt update
  - apt install suricata
  - suricata-update
  - systemctl stop suricata
  - mv /etc/suricata/suricata.yaml /etc/suricata/suricata.yaml.old
  - mv /etc/suricata/suricata.yaml.bak /etc/suricata/suricata.yaml